{% set name = "calver" %}
{% set version = "2025.4.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 460702737d620f5c3d4175450485180a1b7f7a422c5db0e6af3e655c7395ec7e

build:
  skip: true  # [py<39]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools >=77.0.1
  run:
    - python

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - pretend
  imports:
    - calver
  commands:
    - pip check
    - pytest -v tests/

about:
  home: https://github.com/di/calver
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Setuptools extension for CalVer package versions
  description: |
    The calver package is a setuptools extension for automatically
    defining your Python package version as a calendar version.
  doc_url: https://pypi.org/project/calver
  dev_url: https://github.com/di/calver

extra:
  recipe-maintainers:
    - di
    - mgorny
    - hugovk
    - pradyunsg
